"""add user_id to recommendations

Revision ID: 12a82e6df38b
Revises: 4392b1d53edc
Create Date: 2026-07-07 18:50:14.670150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12a82e6df38b'
down_revision: Union[str, Sequence[str], None] = '4392b1d53edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'recommendations', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_column('recommendations', 'user_id')
    # ### end Alembic commands ###
