"""add copilot_interactions table

Revision ID: 2404c05c4f28
Revises: 12a82e6df38b
Create Date: 2026-07-08 20:14:09.876937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2404c05c4f28'
down_revision: Union[str, Sequence[str], None] = '12a82e6df38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('telemetry_included', sa.Boolean(), nullable=True),
    sa.Column('was_helpful', sa.Boolean(), nullable=True),
    sa.Column('folded_into_kb', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_interactions_id'), 'copilot_interactions', ['id'], unique=False)
    op.create_index(op.f('ix_copilot_interactions_user_id'), 'copilot_interactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copilot_interactions_user_id'), table_name='copilot_interactions')
    op.drop_index(op.f('ix_copilot_interactions_id'), table_name='copilot_interactions')
    op.drop_table('copilot_interactions')
    # ### end Alembic commands ###
