"""initial schema

Revision ID: b5d67395f5af
Revises: 
Create Date: 2026-07-02 17:20:01.429382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d67395f5af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('systems',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cpu', sa.String(), nullable=True),
    sa.Column('gpu', sa.String(), nullable=True),
    sa.Column('ram_gb', sa.Integer(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_systems_system_id'), 'systems', ['system_id'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('game_genre', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('preset', sa.String(), nullable=True),
    sa.Column('ray_tracing', sa.Boolean(), nullable=True),
    sa.Column('upscaling', sa.String(), nullable=True),
    sa.Column('predicted_fps', sa.Float(), nullable=True),
    sa.Column('low_1pct_fps', sa.Float(), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('bottleneck_class', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['systems.system_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_predictions_prediction_id'), 'predictions', ['prediction_id'], unique=False)
    op.create_table('telemetry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('cpu_usage', sa.Float(), nullable=True),
    sa.Column('gpu_usage', sa.Float(), nullable=True),
    sa.Column('vram_used_gb', sa.Float(), nullable=True),
    sa.Column('gpu_temp', sa.Float(), nullable=True),
    sa.Column('ram_usage', sa.Float(), nullable=True),
    sa.Column('gpu_clock_mhz', sa.Float(), nullable=True),
    sa.Column('gpu_power_w', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['systems.system_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_id'), 'telemetry', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('estimated_fps_gain', sa.Float(), nullable=True),
    sa.Column('was_helpful', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.prediction_id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_index(op.f('ix_recommendations_recommendation_id'), 'recommendations', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_recommendation_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_telemetry_id'), table_name='telemetry')
    op.drop_table('telemetry')
    op.drop_index(op.f('ix_predictions_prediction_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_systems_system_id'), table_name='systems')
    op.drop_table('systems')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
